### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by jaydipdalal** [jaydipdalal/product_haunt#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by samwalker191** [comment]
Looks good! Just a few recommendations. Please see below:

![image](https://user-images.githubusercontent.com/49164119/72301779-bf9dde80-361c-11ea-914e-98ec1afce2f2.png)

---

![image](https://user-images.githubusercontent.com/49164119/72301786-c298cf00-361c-11ea-9672-82d9de6c70b6.png)

---

![image](https://user-images.githubusercontent.com/49164119/72301795-c75d8300-361c-11ea-9a32-da9960efd8ae.png)

---

![image](https://user-images.githubusercontent.com/49164119/72301798-cb89a080-361c-11ea-8f49-2ed0a5edc1b3.png)

**Comment by jaydipdalal** [comment]
Updated!

**Comment by jaydipdalal** [comment]
Updated again! (With corrections for new bug, where form fields were resizing on click/hover.)
